services:
  app:
    build: .
    container_name: tasks-api
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      AWS_REGION: ap-south-1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    env_file:
      - .env
